[package]
name = "channels"
version = "0.1.0"
authors = ["Shankar Nagarajan <shankar.nagarajan@firstwavecloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
